### ISSUE TITLE
Server crashing when sending a message from Discord

### ISSUE THREAD

**Issue by vinceeleazar** [arthurbambou/Fabric---Discord-Link#104]
Latest version of Fabric Discord Link : 0.7.1
Crash log: https://mclo.gs/GguffDr

Thanks in advance :)

**Comment by vinceeleazar** [comment]
Hmm the server is still crashing in the latest mod version (0.7.3) and latest fabric API (fabric-api-0.21.0+build.407-1.16). Although it looks like it's whole other reason. Should I close this and create a new issue? 
Anyway here are the logs, thanks in advance. 
server log: https://mclo.gs/AxSZlYv
crash log: https://mclo.gs/pEKSJyu

**Comment by thecatcore** [comment]
fixed in 0.7.4

**Comment by vinceeleazar** [comment]
thank you!
