### ISSUE TITLE
[Important] New Discord API Changes and Requirements

### ISSUE THREAD

**Issue by BNTFryingPan** [arthurbambou/Fabric---Discord-Link#106]
Here is a list of changes that may or may not be fixed already, but are important to make sure are fixed

- On May 4th, discord announced that they are migrating most of the API from `discordapp.com` to `discord.com`. Currently both are supported, however on November 7th, `discordapp.com` will no longer work, and all applications and bots currently using it will no longer function.
- On October 7th, bots that are in more than 100 servers or more, and are not verified will be unable to join more servers. Getting a bot verified requires legal identification. You can read discords [blog post](https://support.discord.com/hc/en-us/articles/360040720412) about this. Bots can get verified once they are in 75 or more servers, and will only be restricting once reaching 100 servers.
- Discord is updating its API from v6 to v8. v8 is not "finished" yet from discords end, so v6 will still be around for a while, however v8 has many breaking changes that should be accounted for. v6 is also getting new features like intents, which will not allow bots to access Guild Members or Presences unless you either have the bot ask for this intent when connecting to discord, or by enabling it in the Developer Dashboard.

A lot of this stuff is probably covered by whatever discord library you use (assuming you do in fact use one), but I am sharing this just to be sure you are aware of these changes, and so you update the library if you have not recently.

**Comment by thecatcore** [comment]
I’m using a library so all of this is handled by it but thanks for sharing it, I’ll the library frequently for update.

**Comment by BNTFryingPan** [comment]
Great, just wanted to make sure you knew about it so you (hopefully) don't get as many angry people saying "why does it not work now" or something like that. Although I'm sure you will still get some from people who refuse to update.
