### ISSUE TITLE
Make discord channel topic configurable

### ISSUE THREAD

**Issue by kwvanderlinde** [arthurbambou/Fabric---Discord-Link#110]
**Is your feature request related to a problem?**
The configuration supports the `"customChannelDescription"` flag to automatically update the discord topic every few minutes. But there isn't anything "custom" about the description as the format is hardcoded to look like this:
```
Playercount : 3/20,
Uptime : 120h 1m 24s
```

**The suggestion**
The channel description should support a custom format string that is used to generate the actual channel topic that gets set. Various placeholders can be used in the same way as for custom messages. The set of placeholders should include:
- `%playercount`: The current number of players connected to the server
- `%maxplayercount`: The maximum number of players that can connect to the server at once.
- `%uptime`: The uptime of the server, formatted to include hours, minutes, and seconds.
- `%motd`: The server's message of the day.
- `%datetime`:  The current date and time, formatted to include day, month, year, hours, minutes, and seconds.
- others??

For parity with current behaviour, the default format string should be `"Playercount : %playercount/%maxplayercount, Uptime : %uptime"`. This format can be modified by changing value of `minecraftToDiscord.messages.channelDescription` in `fdlink.json`.

**Alternatives**
Since the topic string is hardcoded, there are no alternatives to achieving a custom channel topic with dynamic parameters.

**Comment by thecatcore** [comment]
Implemented in 0.7.9:
- channel description is customizable
- added placeholders:

    - `%playercount`: The current number of players connected to the server
    - `%maxplayercount`: The maximum number of players that can connect to the server at once.
    - `%uptime`: The uptime of the server, formatted to include days, hours, minutes, and seconds.
    - `%motd`: The server's message of the day.
    - `%uptime_d`: The day uptime of the server.
    - `%uptime_h`: The hour uptime of the server.
    - `%uptime_m`: The minute uptime of the server.
    - `%uptime_s`: The second uptime of the server.
    - `%uptime` is equal to: "%uptime_dd %uptime_hh %uptime_mm %uptime_ss"
