### ISSUE TITLE
when ignoreBots is false, the bot reads its own messages

### ISSUE THREAD

**Issue by w1lldu** [arthurbambou/Fabric---Discord-Link#123]
**Describe the bug**
The bot sends messages from the Minecraft server to the Discord server, but since it does not ignore its own messages, those messages get sent back to the Minecraft server.

**Reproduction steps**
set ignoreBots to false in fdlink.json

**Expected behaviour**
The bot should react to messages sent by other bots but not its own, thus not sending a player's message back into the server.
For example, if I (on the Minecraft Server) send a message, the bot sends a message on Discord, sees its own message, and does nothing.

**Additional context**
Mods are not the problem, the only thing changes between tests was the ignoreBots value.

**fdlink.json**
ignoreBots = false

**Comment by thecatcore** [comment]
Fixed in 0.8.2 when it's released in a few minutes.
