### ISSUE TITLE
Webhook support!

### ISSUE THREAD

**Issue by ElijahRus250** [arthurbambou/Fabric---Discord-Link#126]
**Is your feature request related to a problem?**
I think that if you were to add web hook support, it would make it a lot better to read chat.

**The suggestion**
Webhook support to make chat messages look like this 
<img width="396" alt="Screen Shot 2021-01-16 at 6 22 45 PM" src="https://user-images.githubusercontent.com/64851720/104827046-d70f3900-5827-11eb-9b79-9e4d562724bf.png">

**Alternatives**
No

**Comment by thecatcore** [comment]
It is supported

**Comment by thecatcore** [comment]
Also duplicate of #80
