### ISSUE TITLE
Weird messages in console

### ISSUE THREAD

**Issue by xAlicatt** [arthurbambou/Fabric---Discord-Link#14]
I'm not 100% sure it's this mod causing it, but I dunno what else would. 

I'm getting messages like these spamming console every time someone chats in-game:

`[Server] Server thread/INFO [STDOUT]: TranslatableComponent{key='chat.type.text', args=[TextComponent{text='PoetForTheDead', siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=ClickEvent{action=SUGGEST_COMMAND, value='/tell PoetForTheDead '}, hoverEvent=HoverEvent{action=SHOW_ENTITY, value='TextComponent{text='{name:'{"text":"PoetForTheDead"}',id:"eb6bbf38-1e8e-44cf-a332-53587257b95b",type:"minecraft:player"}', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}'}, insertion=PoetForTheDead}}, I can read I swear], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}`

And then messages like these every time someone chats in discord:

`[Server] Server thread/INFO [STDOUT]: TextComponent{text='[Alicatt] i can type', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}`

And these when people login or out:

`[Server] Server thread/INFO [STDOUT]: TranslatableComponent{key='multiplayer.player.joined', args=[TextComponent{text='Kodamasa_', siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=ClickEvent{action=SUGGEST_COMMAND, value='/tell Kodamasa_ '}, hoverEvent=HoverEvent{action=SHOW_ENTITY, value='TextComponent{text='{name:'{"text":"Kodamasa_"}',id:"90e367d8-7595-4080-95b6-f823182379eb",type:"minecraft:player"}', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}'}, insertion=Kodamasa_}}], siblings=[], style=Style{hasParent=false, color=, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}`

`[Server] Server thread/INFO [STDOUT]: TranslatableComponent{key='multiplayer.player.left', args=[TextComponent{text='Kodamasa_', siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=ClickEvent{action=SUGGEST_COMMAND, value='/tell Kodamasa_ '}, hoverEvent=HoverEvent{action=SHOW_ENTITY, value='TextComponent{text='{name:'{"text":"Kodamasa_"}',id:"90e367d8-7595-4080-95b6-f823182379eb",type:"minecraft:player"}', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}'}, insertion=Kodamasa_}}], siblings=[], style=Style{hasParent=false, color=, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}`

And some of them are partly yellow as well....so something is wonky in the code I think.

**Comment by thecatcore** [comment]
Oh yes, I forgot to remove debug messages xD.
I will fix this tomorrow.

**Comment by xAlicatt** [comment]
Poke?

**Comment by xAlicatt** [comment]
Hey, sorry to bother, but it still doing it in the newest update. Do i need to regen the config?
