### ISSUE TITLE
Incompatibility with Fabric Console

### ISSUE THREAD

**Issue by srnyx** [arthurbambou/Fabric---Discord-Link#142]
**Describe the bug**
Not getting join/leave/chat messages from MC to Discord

**Additional context**
- Minecraft version: 1.16.5
- Fabric-Discord Link version: 0.8.18
- :exclamation: A list of all mods you were using: A lot... (around 123)

**fdlink.json**
[fdlink.txt](https://github.com/arthurbambou/Fabric---Discord-Link/files/6299543/fdlink.txt)

**Comment by thecatcore** [comment]
Can you send the mod list?

**Comment by srnyx** [comment]
> Can you send the mod list?

Ok, but do you know ANY easy way to do it?
I hate taking like 5 screenshots every time I want to send it.

**Comment by srnyx** [comment]
> Can you send the mod list?

https://imgur.com/a/gg4lv67
_Also, I just recently added [fabric-discord-integration](https://github.com/hkva/fabric-discord-integration) to test it out, then removed it afterward, not sure if that caused this._

**Comment by thecatcore** [comment]
🤦‍♂️ I think I broke compatibility with fabric-console again. Can you try without it?

**Comment by srnyx** [comment]
> Can you try without it?

Yep, works without it.

**Comment by srnyx** [comment]
Any updates?
