### ISSUE TITLE
1.17 Support

### ISSUE THREAD

**Issue by apple502j** [arthurbambou/Fabric---Discord-Link#151]
**Is your feature request related to a problem?**
I want axolotls in my server while chatting with Discord.

**The suggestion**
Add 1.17 support

**Alternatives**
Develop my own mod

**Comment by Patbox** [comment]
From my test latest version works just fine on 1.17 (from modrinth)

**Comment by thecatcore** [comment]
On curseforge too it supports 1.17
I don’t see why you would think it doesn’t 🤔

**Comment by apple502j** [comment]
Thanks
