### ISSUE TITLE
Unicode glyphs serialized wrongly.

### ISSUE THREAD

**Issue by Creta5164** [arthurbambou/Fabric---Discord-Link#169]
**Describe the bug**
I tried to use the `messages.json` file in the config after translating it to the managed server, but every time I run the server, the characters in the Unicode range are broken.

Gist : https://gist.github.com/Creta5164/3771c9651ecd442585210d77c8a57fdf  
(Read comments too)

**Reproduction steps**
1. Setup Fabric server with this mod.
2. Copy json https://gist.github.com/Creta5164/3771c9651ecd442585210d77c8a57fdf to `config/fdlink/messages.json`
3. Launch server
4. Content of `messages.json` turns into unknown characters every unicode characters (Korean in this case)

**Expected behaviour**
`messages.json` keep stay it's content.

**Additional context**
- Minecraft version: Fabric `1.17.1`
- Fabric-Discord Link version: `0.9.7`
- :exclamation: A list of all mods you were using: Medieval Minecraft FABRIC `16.5`
https://www.curseforge.com/minecraft/modpacks/medieval-minecraft-fabric

**Comment by thecatcore** [comment]
Will be fixed in 0.10.1.
