### ISSUE TITLE
Server crashes with mod

### ISSUE THREAD

**Issue by srnyx** [arthurbambou/Fabric---Discord-Link#172]
**Additional context**
- Minecraft version: 1.17.1
- Fabric-Discord Link version: 0.9.6
- Error: https://paste.srnyx.xyz/riqefenulo.sql
- :exclamation: A list of all mods you were using: https://github.com/srnyx/mc-server-templates/tree/main/Fabric%201.17.1/mods

**fdlink.json**
Default

**Comment by arthurbambou** [comment]
What version of fabric loader do you have?

**Comment by thecatcore** [comment]
Please use latest version of fdlink which is 0.9.8
