### ISSUE TITLE
I don't have fdlink.json in my config folder

### ISSUE THREAD

**Issue by Technologx** [arthurbambou/Fabric---Discord-Link#176]
**Describe the bug**

I don't have fdlink.json in my config folder. I restarted the server several times to see if it would generate and I still don't see it.
**Reproduction steps**

I just installed the mod and restarted the server

**Expected behaviour**

I expect to have fdlink.json so I can link the game chat to my discord server.
<details> 
  <summary><strong>Crash report</strong></summary>
 

```

```

</details>

**Additional context**

- Minecraft version: 1.18.1
- Fabric-Discord Link version: 0.10.1
- :exclamation: A list of all mods you were using: Valhelsia: Enhanced Vanilla - 1.18

**fdlink.json**
Please attach your configuration file (`fdlink.json`) here (edit the token out)

I don't have this file

**Comment by intellectualpancake** [comment]
Do you have the `fdlink-api-0.1.1.jar` file in your mods folder?

**Comment by arthurbambou** [comment]
Can't reproduce.
