### ISSUE TITLE
Switch to Semantic Versioning

### ISSUE THREAD

**Issue by psharma04** [arthurbambou/Fabric---Discord-Link#179]
**Is your feature request related to a problem?**
Currently, Fabric attempts to check the versions of every mod. Since FDLink doesn't use Semantic Versioning, it dumps a whole list of warnings for the mod:
`[main/WARN]: Mod `fdlink` (${version}) does not respect SemVer - comparison support is limited.
[main/WARN]: Mod `fdlink_1_12_2` (${version}) does not respect SemVer - comparison support is limited.
[main/WARN]: Mod `fdlink_1_15_2` (${version}) does not respect SemVer - comparison support is limited.
[main/WARN]: Mod `fdlink_1_16` (${version}) does not respect SemVer - comparison support is limited.
[main/WARN]: Mod `fdlink_1_7_10` (${version}) does not respect SemVer - comparison support is limited.
[main/WARN]: Mod `fdlink_1_8_9` (${version}) does not respect SemVer - comparison support is limited.
[main/WARN]: Mod `fdlink_api` (${version}) does not respect SemVer - comparison support is limited.
[main/WARN]: Mod `fdlink_common` (${version}) does not respect SemVer - comparison support is limited.`

**The suggestion**
Use [semantic versioning](https://semver.org/) in order to remove these warnings.

**Comment by thecatcore** [comment]
is this in dev environment or production?

**Comment by thecatcore** [comment]
oops, I think I broke it recently, will fix in the next 24h

**Comment by thecatcore** [comment]
Fixed in 0.10.4+ ~~(when it releases)~~

**Comment by psharma04** [comment]
This was in the production version from CurseForge.
