### ISSUE TITLE
Logs are broke while using this mod

### ISSUE THREAD

**Issue by cherie535** [arthurbambou/Fabric---Discord-Link#181]
**Describe the bug**
Not all normal logging is happening.  For instance, the normal:

[00:32:39] [User Authenticator #1/INFO]: UUID of player player is 5aasdas-4sdfsdf-4dsfsdf-a37f-c5b9dsdfsdfcdbdc
[00:32:39] [Server thread/INFO]: player[/192.168.1.1:36009] logged in with entity id 182 at (7.395296714244613, 64.0, -2.699999988079071)

isnt logged.
Leave messages are not logged either.

**Reproduction steps**

Install mod
check logs

**Expected behaviour**
Normal logging
</details>

**Additional context**

- Minecraft version: 22w03a
- Fabric-Discord Link version: Fabric-Discord-Link-0.10.4
- :exclamation: A list of all mods you were using: fabric-carpet, player-events, styledplayerlist (removing these doesnt help)

**{
  "token": "12345",
  "chatChannels": [
    "8705000123459238805"
  ],
  "logChannels": [
    ""
  ],
  "webhook": {
    "url": "",
    "mentions": {
      "everyone": false,
      "roles": false,
      "users": true
    }
  },
  "ignoreBots": true,
  "activityUpdateInterval": 120,
  "minecraftToDiscord": {
    "general": {
      "enableDebugLogs": false
    },
    "chatChannels": {
      "commandPrefix": "-",
      "allowDiscordCommands": false,
      "serverStartingMessage": true,
      "serverStartMessage": true,
      "serverStopMessage": true,
      "serverStoppingMessage": true,
      "customChannelDescription": false,
      "minecraftToDiscordTag": false,
      "minecraftToDiscordDiscriminator": false,
      "playerMessages": true,
      "teamPlayerMessages": true,
      "joinAndLeaveMessages": true,
      "advancementMessages": true,
      "challengeMessages": true,
      "goalMessages": true,
      "deathMessages": true,
      "sendMeCommand": true,
      "sendSayCommand": true,
      "adminMessages": false,
      "atATellRaw": false,
      "achievementMessages": true
    },
....
**

**Comment by cherie535** [comment]
Actually, literally, nothing is being logged, acheivements, deaths, etc..

The only thing in the latest.log is chat.

**Comment by cherie535** [comment]
AND, to go even further, the only chat in the log is discord chat.  server chat isnt in the log.

wierd.

**Comment by thecatcore** [comment]
Hm, have you tested without FDLink? With Fabric Loader only?

**Comment by cherie535** [comment]
if I remove this mod, logging is normal, so yes.

PS:

I hope I dont sound short or irritatated.  This is the VERY nicest discord bridge I have found, slick AF, so I was super sad when I discovered the lack of logging.  I suspect maybe something has chnaged in the most recent snapshot.

**Comment by cherie535** [comment]
I did go back just to make sure, and yes, running this with all by itself (no other mods) breaks the normal logging in the latest mc snapshot.  Everything else is flawless.

**Comment by thecatcore** [comment]
can you try again with 0.10.5 this time?

**Comment by wh0oo** [comment]
binary?

**Comment by thecatcore** [comment]
ugh, rebuilding rn

**Comment by wh0oo** [comment]
No improvement. :(

**Comment by wh0oo** [comment]
here is the latest.log with just fabric-api.

https://pastebin.com/hP6b9fAN

**Comment by thecatcore** [comment]
try with 0.10.6

**Comment by wh0oo** [comment]
logging is working with 0.10.6.  thanks!

**Comment by thecatcore** [comment]
Awesome
