### ISSUE TITLE
build fails!

### ISSUE THREAD

**Issue by VitasLoWang** [arthurbambou/Fabric---Discord-Link#190]
gradlew build
after 6 minutes I get
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':common:remapJar'.
> Could not resolve all dependencies for configuration ':common:include'.
   > Could not find or.slf4j:slf4j-api:1.8.0-beta4.
     Searched in the following locations:
       - file:/C:/GIT/Fabric---Discord-Link/.gradle/loom-cache/remapped_mods/or/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.
8.0-beta4.pom
       - https://maven.fabricmc.net/or/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.pom
       - https://libraries.minecraft.net/or/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.pom
       - https://libraries.minecraft.net/or/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
       - https://repo.maven.apache.org/maven2/or/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.pom
       - file:/C:/Users/Administrator.VITAS-SERVER.000/.gradle/caches/fabric-loom/1.8.0-beta4/slf4j-api.jar
       - file:/C:/GIT/Fabric---Discord-Link/.gradle/loom-cache/1.8.0-beta4/slf4j-api.jar
       - file:/C:/Users/Administrator.VITAS-SERVER.000/.m2/repository/or/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-bet
a4.pom
       - https://m2.dv8tion.net/releases/or/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.pom
       - https://maven.legacyfabric.net/or/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.pom
       - https://jitpack.io/or/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.pom
     Required by:
         project :common

**Comment by thecatcore** [comment]
fixed in latest commit
