### ISSUE TITLE
crash when joining server

### ISSUE THREAD

**Issue by Gbergz** [arthurbambou/Fabric---Discord-Link#3]
Server Crash report: https://paste.ee/p/f395R

Simply just joining the server and it crashes.

**Comment by thecatcore** [comment]
You need to add the bot token to the config file on your server

It's my fault, I hadn't written an article explaining it yet.

Now there is one: https://github.com/arthurbambou/Fabric---Discord-Link/wiki/How-to-get-a-token-and-channel-ID-for-Discord

**Comment by thecatcore** [comment]
Fixed in : https://minecraft.curseforge.com/projects/fabric-discord-link/files/2712828
