### ISSUE TITLE
1.15.2 server crash on client join

### ISSUE THREAD

**Issue by SDUBZ** [arthurbambou/Fabric---Discord-Link#55]
FD: FDLink-0.2.7
crash : 
[crash-2020-01-30_20.57.00-server.txt](https://github.com/arthurbambou/Fabric---Discord-Link/files/4133384/crash-2020-01-30_20.57.00-server.txt)

logs: 
[latest.log](https://github.com/arthurbambou/Fabric---Discord-Link/files/4133385/latest.log)

**Comment by thecatcore** [comment]
can you send FDLink your config file? I need it to understand why it crashed.
