### ISSUE TITLE
Random Crash on 0.2.6 No clue what caused it

### ISSUE THREAD

**Issue by furtabs** [arthurbambou/Fabric---Discord-Link#56]
https://pastebin.com/nMXQPkhi

**Comment by thecatcore** [comment]
Your game is crashing because of modmenu, can you try changing the version of it?
It's not related at all to Fabric Discord Link.

**Comment by coderbot16** [comment]
Modmenu is not even loaded in the log, this is a server crash. Can this be re-opened?

**Comment by thecatcore** [comment]
🤔 I think I opened the wrong crash report... but still, it should be fix in 0.2.8
