### ISSUE TITLE
Using the mod disables the ability to chat ingame

### ISSUE THREAD

**Issue by juneflowers** [arthurbambou/Fabric---Discord-Link#60]
Hey this one totally stumped me, I didn't even think it was this mod at first and just maybe a setting I missed somewhere, but I narrowed it down to the problem being the mod. While enabled We cannot talk in game. Discord chat shows up in game however. When I disabled the mod then we could chat ingame again. Is it not meant to work both ways?

**Comment by thecatcore** [comment]
What version of Minecraft are you using? Can you send your config file so I can take a look at it?

**Comment by juneflowers** [comment]
1.15.2 and sure heres the config
https://paste.duck.casa/?4e1fcf57fec06c4e#85Hipu8ivi8iuruRricVL3QtfYHAR3Rxq2TeTcEMDcV5

**Comment by thecatcore** [comment]
what other mods do you have installed?

**Comment by juneflowers** [comment]
Heres a folder with all the mods
https://cloud.duck.casa/s/dCeM9BE78ggfMxG

**Comment by thecatcore** [comment]
Can't reproduce it
