### ISSUE TITLE
Wrong server uptime

### ISSUE THREAD

**Issue by TalEdd** [arthurbambou/Fabric---Discord-Link#61]
The server uptime is displaying wrongly for me on Discord. When the server is up for 30 mins, it shows 30 seconds. Hours show minutes, minutes show as seconds. Is there a config I can change or is there a fix for this?

**Comment by Thedude7054** [comment]
Working on it. Thanks for reporting this.

**Comment by TalEdd** [comment]
No problem. I have one more question. Is there a way to send commands from Discord to Minecraft, as it would make server management much easier, maybe possibly through logs channel?

**Comment by thecatcore** [comment]
should be fixed normally
