### ISSUE TITLE
Server Log Messages are Not Relayed

### ISSUE THREAD

**Issue by ghost** [arthurbambou/Fabric---Discord-Link#62]
Player messages go into discord chat but server logs do not.
Here is my config file

```json
{
  "token": "NjY4NDY5NzA5NjMyNTY5MzY0.XprZ7A.8PhrkiCh3fdyACKYtq4YYQwloFY",
  "discordToMinecraft": "<%player> %message",
  "chatChannels": [
    "701009107859144745"
  ],
  "logChannels": [
    "701013116279849000"
  ],
  "ignoreBots": true,
  "minecraftToDiscord": {
    "messages": {
      "serverStarting": "Server is starting!",
      "serverStarted": "Server Started",
      "serverStopped": "Server Stopped"
    },
    "booleans": {
      "customChannelDescription": false,
      "MCtoDiscordTag": false,
      "PlayerMessages": true,
      "JoinAndLeftMessages": true,
      "AdvancementMessages": true,
      "LogMessages": true,
      "DeathMessages": true
    }
  }
}
```
My bot is [here](https://discordapp.com/developers/applications/668469709632569364/information). If you can't view it and need to, tell me what to do so you can.

**Comment by ghost** [comment]
First things first, you should never post your Bot token anywhere (and I suggest you regenerate it, as people could use your bot without your consent).
Second, we can't access your bot since it's on your account.

**Comment by ghost** [comment]
Can you help me with this issue without access to the bot?

**Comment by thecatcore** [comment]
Can't reproduce it
