### ISSUE TITLE
[1.16-20w19a] Crashes as soon as I launch server.

### ISSUE THREAD

**Issue by Gbergz** [arthurbambou/Fabric---Discord-Link#67]
Hey, can't get this to work on the latest snapshot 20W19A.
Is this known?

- Gbergz

Using latest version released: FDLink-0.3.3.jar [1.16]
Fabric API version: [20w19a] Fabric API 0.10.7 build 344

Screenshot: 
![image](https://user-images.githubusercontent.com/26634554/81478500-3e4b0700-921e-11ea-96de-7314c0c07cf9.png)

**Comment by thecatcore** [comment]
fixed by https://www.curseforge.com/minecraft/mc-mods/fabric-discord-link/files/2952459 :-)

**Comment by Gbergz** [comment]
Wow that was fast, thank you! :)
