### ISSUE TITLE
[1.16-20w21a] Mod broke on this snapshot, just letting you know.

### ISSUE THREAD

**Issue by Gbergz** [arthurbambou/Fabric---Discord-Link#70]
Title^

Snapshot: 20w21a - 1.16
Loader Version: 0.8.4+build198
Fabric API: fabric-api-0.10.10+build.347-1.16
FDLink Used: 0.3.4

Any ideas?

**Comment by thecatcore** [comment]
can you send the crash report?

**Comment by Gbergz** [comment]
There's no Crash report but i'll lend you the logs here: https://gist.github.com/Gbergz/adde80c7b9492d639d918e9ae91c8ba9

**Comment by thecatcore** [comment]
you can use this version : https://www.curseforge.com/minecraft/mc-mods/fabric-discord-link/files/2962187
