### ISSUE TITLE
Add edit/localization for join/leave message

### ISSUE THREAD

**Issue by JoCat** [arthurbambou/Fabric---Discord-Link#71]
Please add the ability to change the message to enter and exit the server.
![image](https://user-images.githubusercontent.com/13483132/83682749-0781ca00-a5ed-11ea-8223-b320ea8935c0.png)

**Comment by JoCat** [comment]
👎 ok, I'll write it myself

**Comment by thecatcore** [comment]
The issue has been closed because I've released a build of FDLink with this functionality.

**Comment by thecatcore** [comment]
1.14-1.15: https://www.curseforge.com/minecraft/mc-mods/fabric-discord-link/files/2974210
1.16: https://www.curseforge.com/minecraft/mc-mods/fabric-discord-link/files/2974213

**Comment by JoCat** [comment]
wow, that's better already, thanks 👍
