### ISSUE TITLE
Escape player usernames in discord

### ISSUE THREAD

**Issue by PssbleTrngle** [arthurbambou/Fabric---Discord-Link#74]
If a players name, for example contains text being used by discord to format, for example `x__gamer__x`, this text will be displayed in discord formatted.
Escaping usernames like `x_gamer_x` -> `x\_gamer\_x` would prevent this.

**Comment by thecatcore** [comment]
working on fixing it

**Comment by PssbleTrngle** [comment]
I think everything that needs escaping are asterisks, undescores, backticks and backslashes by putting a blackslash in front of it somewhere in there:
https://github.com/arthurbambou/Fabric---Discord-Link/blob/c7d8ffd69f6a407597ca39c7bb2caa08a08d08cc/src/main/java/fr/arthurbambou/fdlink/discordstuff/DiscordBot.java#L234
