### ISSUE TITLE
[QUESTION] Localizating messages

### ISSUE THREAD

**Issue by PssbleTrngle** [arthurbambou/Fabric---Discord-Link#78]
I was wondering how the mod gets the server message like advancements and player join/leave messages.
Is it getting the already formatted text, or the message class and if it's the second case, is their a possiblity to provide a custom language file to format the messages?

**Comment by thecatcore** [comment]
In the last version of Fabric-Discord Link, you can customize most messages in the config file
![image](https://user-images.githubusercontent.com/34719527/86294920-c8e42d00-bbf5-11ea-8a04-8292726c3f8c.png)

**Comment by allethargic** [comment]
I've localised messages in this file to Russian and it looks weird in discord. Fix?
![image](https://user-images.githubusercontent.com/68805541/88536396-6a537880-d014-11ea-91a0-fb413b463957.png)

**Comment by thecatcore** [comment]
🤔

**Comment by allethargic** [comment]
Perhaps some weird unicode shenanigans?

**Comment by AlexanderRitter02** [comment]
@allethargic Please attach the `fdlink.json` file you are using for that.

**Comment by allethargic** [comment]
Well, I deleted mod after that bug, but I was able to recreate json file. 
[fdlink.zip](https://github.com/arthurbambou/Fabric---Discord-Link/files/5010233/fdlink.zip)

**Comment by AlexanderRitter02** [comment]
This is really strange.
When running a server in the development environment it works fine, but when taking the .jar on a seperate server I can reproduce your issue.

**Comment by allethargic** [comment]
Look up similar mods for Forge maybe? Before I was using one of them and seen no such problems.
