### ISSUE TITLE
Webhooks Support

### ISSUE THREAD

**Issue by Ictoan42** [arthurbambou/Fabric---Discord-Link#80]
Sorry if this exists and I'm not seeing it, but webhooks is a feature that would enhance the mod greatly, is largely the draw of DiscordSRV, and would make the mod generally much better.

**Comment by vico93** [comment]
I second this.

If this is implemented in a similar way to disfabric (_image_) that would be good.

![image](https://user-images.githubusercontent.com/3485505/94494599-f6754e00-01c5-11eb-814a-5afbe76e0f55.png)

**Comment by MightyKnight** [comment]
[DisFabric](https://github.com/BRForgers/DisFabric) does not have a license and All Rights Reserved on Curseforge...

But [Discord-Fabric Link](https://github.com/HeyItsMeNobody/discordfabriclink) also implements webhooks under CC0, which means we may be able to integrate it.

**Comment by vico93** [comment]
> [DisFabric](https://github.com/BRForgers/DisFabric) does not have a license and All Rights Reserved on Curseforge...
> 
> But [Discord-Fabric Link](https://github.com/HeyItsMeNobody/discordfabriclink) also implements webhooks under CC0, which means we may be able to integrate it.

> If this is implemented **_in a similar way_** to disfabric

**Comment by thecatcore** [comment]
Implemented in 0.8.0 :smile:
