### ISSUE TITLE
Make death message configurable

### ISSUE THREAD

**Issue by AlexanderRitter02** [arthurbambou/Fabric---Discord-Link#81]
### Problem
Death messages like _"Player was slain by Silverfish"_ can't be modified in the config.
However, I would like to be able to **append** or prepend emojis or even just set a **static message**.

Example:
![grafik](https://user-images.githubusercontent.com/42546705/86568312-f40bab00-bf6c-11ea-86db-fa87fe6eec62.png)

### The suggestion
Seeing as pretty much all messages (playerJoined etc.) are already configurable, I wish there was support for setting a custom **death message** as well.

As for replacable things in the config, I suggest having:
1. `%player:` The name of the player who died, extracted from the death event
2. `%deathmsg`: Part of the death string after the player name (e.g. _was slain by Silverfish_).
Should be achievable by _splitting_ the string, as it seems like vanilla death messages always adhere to the same format, being: `playername was ...`.

Here's what the **default** config option should look like:
```
"minecraftToDiscord": {
      "messages": {
            ...
            "deathMessage": "%player %deathmsg",
            ...
      }
}
```

**Comment by v-tron** [comment]
Due to the sheer number of death messages (about 30 or 40 I think) in the game this is going to be quite tedious to implement fully (as in make all possible messages completely customizable) since there are a lot of possible messages with one to three entities involved. 

In my pull request I added the feature to add a prefix as well as a postfix to the vanilla death messages since that was very easy to implement and already does what you wanted.
Implementing a static custom message is also easy but that is kinda lame no?

**Comment by AlexanderRitter02** [comment]
A static message could be used for example for _"%player has been eliminated from the hunger games event"_ or something like that.

I saw you implemented death messages with deathMsgPrefix and deathMsgPostfix.

You could propably solve the static message by setting the prefix to `%player been eliminated from the hunger games event (` and postfix to `)`, which would result in:
`Player has been eliminated from the hunger games event (Player was slain by blablabla)`.

That seems good enough and doesn't require yet another option.

@v-tron However for that to work you need to be able to use a **%player object** in prefixes and postfixes. ~~Is that possible currently?~~
It doesn't work. I left a comment under your pull request, you may want to add it before merge?

**Comment by v-tron** [comment]
For now I think that the prefix and postfix is enough. But yeah, that could be a way to implement it. I was thinking about a custom death messages part of the config where you could customize messages for each cause of death (fell out of the world, shot by, etc.).
