### ISSUE TITLE
Config option "joinAndLeftMessages" is gramatically inconsistent

### ISSUE THREAD

**Issue by AlexanderRitter02** [arthurbambou/Fabric---Discord-Link#82]
This may be overly picky, but it is still an issue. Propably an oversight.

The boolean option for disabling join and leave messages is **gramatically inconsistent**. (`joinAndLeftMessages`)
"Join" is active and in the present, while "Left" is in the past.

It should either be:
1. `joinedAndLeftMessages`
2. `joinAndLeaveMessages`

I prefer the second option, as the joining/leaving is an active process.

**Comment by thecatcore** [comment]
will be fixed in the next release
