### ISSUE TITLE
Unhandled incorrect escape strings

### ISSUE THREAD

**Issue by trunkyredstone** [arthurbambou/Fabric---Discord-Link#83]
When I send a message from discord containing a \, an error is thrown about an incomplete/incorrect escape string , which causes a server crash:

`java.lang.IllegalArgumentException: character to be escaped is missing`

This has not been tested for the other way

**Comment by PegasusEpsilon** [comment]
Can you test https://pegasus.pimpninjas.org/binaries/FDLink-0.4.2.2.jar and see if this resolves your issue?

Or if you're on an older version of minecraft, let me know.
