### ISSUE TITLE
Mod spams unhandled text messages in the console

### ISSUE THREAD

**Issue by Moranic** [arthurbambou/Fabric---Discord-Link#84]
Whenever any other mod or whatever writes a message to the console, Fabric-Discord link will throw an unhandled text error, duplicating the message before it. This causes a lot of unnecessary spam in the console, and clutters the log.

![image](https://user-images.githubusercontent.com/11034801/87151427-16c2fa00-c2b4-11ea-9079-ccbcc83b5db7.png)

The image is of an example where a chunk pregenerator has all of its messages duplicated by FDLink.

**Comment by PegasusEpsilon** [comment]
https://pegasus.pimpninjas.org/binaries/FDLink-0.4.2.2.jar should resolve this issue.

**Comment by ghost** [comment]
> https://pegasus.pimpninjas.org/binaries/FDLink-0.4.2.2.jar should resolve this issue.

Does for my server.  Thank you!

**Comment by thecatcore** [comment]
I added a option in the config to enable or disable debug log. It's disabled by default ^^.
