### ISSUE TITLE
Server crash due to regex (PR and fixed jar in comments)

### ISSUE THREAD

**Issue by ghost** [arthurbambou/Fabric---Discord-Link#88]
Crash log: https://pastebin.com/V68AktqF

This happens every time someone on Discord's bridge channel types a line containing an $

**Comment by ghost** [comment]
PegasusEpsilon has built a jar that fixes this issue: https://pegasus.pimpninjas.org/binaries/FDLink-0.4.2.1.jar

**Comment by Katorone** [comment]
This jar seems to also fix #84

**Comment by ghost** [comment]
This jar seems to also fix #83

**Comment by PegasusEpsilon** [comment]
New build https://pegasus.pimpninjas.org/binaries/FDLink-0.4.2.2.jar also fixes #84.

I had a poke at #75 while I was at it, but I think that's an architectural problem, and I'm not about to start messing with it that intensely.
